### ISSUE TITLE
Error on installing Hex

### ISSUE THREAD

**Issue by gavintmyers** [annkissam/adify_scripts_for_annkissam#13]
```
==========================================================
Installing Adify 0.1.0.......
==========================================================
fatal: destination path '/Users/backupcomputer15/.cloned_adify' already exists and is not an empty directory.
Already on 'develop'
Your branch is up to date with 'origin/develop'.
==> adify
Could not find Hex, which is needed to build dependency :benchee
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] n
==> adify_runner
** (Mix) Could not find an SCM for dependency :benchee from Adify.MixProject
==> adify
Could not find Hex, which is needed to build dependency :benchee
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] Y

13:07:55.405 [error] Task #PID<0.107.0> started from #PID<0.91.0> terminating
** (MatchError) no match of right hand side value: {:error, {:ssl, {'no such file or directory', 'ssl.app'}}}
    (mix) lib/mix/utils.ex:570: Mix.Utils.read_httpc/1
    (mix) lib/mix/utils.ex:504: anonymous fn/2 in Mix.Utils.read_path/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<4.32372116/0 in Mix.Utils.read_path/2>
    Args: []
** (EXIT from #PID<0.91.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, {:ssl, {'no such file or directory', 'ssl.app'}}}
        (mix) lib/mix/utils.ex:570: Mix.Utils.read_httpc/1
        (mix) lib/mix/utils.ex:504: anonymous fn/2 in Mix.Utils.read_path/2
        (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3


==========================================================
Checking Adify installation.......
==========================================================
==> adify
Could not find Hex, which is needed to build dependency :benchee
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn]
```

**Comment by aditya7iyengar** [comment]
Open ssl problems.
